export const EVENTS_CONSTANT = [
  // Major Global Conferences
  "AWS re:Invent",
  "Microsoft Build",
  "Google I/O",
  "Apple WWDC",
  "GitHub Universe",
  "KubeCon + CloudNativeCon",
  "DockerCon",
  "PyCon US",
  "JSConf Global",
  "Def Con",
  "Black Hat USA",
  "Web Summit",
  "The Next Web (TNW)",
  "QCon London",
  "Microsoft Ignite",
  "Google Cloud Next",
  "Oracle CloudWorld",
  "Adobe Summit",
  "Slack Frontiers",
  "HashiConf",

  // Hackathons & Sprints
  "Hacktoberfest",
  "Global Game Jam",
  "AngelHack",
  "TechCrunch Disrupt Hack",
  "MLH Local Hack Day",
  "Node.js Interactive Sprints",
  "Open Source Saturday",
  "NASA Space Apps Challenge",
  "EthGlobal",
  "Solana Breakpoint",
  "Code for America Summit",
  "Rails Girls Workshop",
  "DjangoGirls",
  "Hard Fork Hack",
  "ByteSized Hackathon",
  "The Big Code Challenge",
  "Zero Trust World",
  "CryptoForge",
  "AppBlitz",
  "Build with Gemini Summit",

  // Meetup & Community Style
  "React Beer Night",
  "Pythonistas Monthly",
  "DevOps Days",
  "Fullstack Founders",
  "The Frontend Collective",
  "Backend & Brews",
  "Data Science Social",
  "Agile Coffee",
  "Rustaceans Retreat",
  "The Gophers Gathering",
  "C# Corner Live",
  "Flutter Flow Meetup",
  "Laravel Live",
  "Vue Mastery Workshop",
  "Wasm Weekend",
  "API World",
  "Microservices March",
  "Serverless Saturday",
  "Kubernetes Community Day",
  "Linux Foundation Summit",

  // Corporate & Internal Dev Event Concepts
  "Internal Innovation Sprint",
  "Legacy Code Cleanup Day",
  "Architecture Review Board",
  "Lunch and Learn: AI Edition",
  "Dev Experience Expo",
  "Engineering Excellence Week",
  "Cloud Migration Workshop",
  "Security Awareness Jam",
  "UX/UI Design Sprint",
  "Quality Assurance Gala",
  "The Refactor Rodeo",
  "API Strategy Summit",
  "Scalability Symposium",
  "The Debugging Derby",
  "Cybersecurity Shield",

  // Creative/Futuristic Names
  "CodeConflux",
  "Quantum Quandary",
  "NeuralNexus",
  "Silicon Synergy",
  "ByteBlast",
  "Algorithm Arena",
  "Digital Dynamo",
  "FutureFlux",
  "CyberSynapse",
  "Infotech Inception",
  "TitanTech Summit",
  "Binary Blast",
  "Matrix Meetup",
  "Edge Computing Expo",
  "Web3 Waves",
  "Prompt Engineering Party",
  "Low-Code Loft",
  "DevRelCon",
  "The Documentation Derby",
  "Open Source Odyssey",
  "SaaS Solutions Summit",
  "The Deployment Disco",
  "CI/CD Carnival",
  "GraphQL Gala",
  "Tailwind Track",
];
