const EVENTS_CONSTANT = [
  // Hackathons & Sprints
  "Hacktoberfest",
  "Global Game Jam",
  "AngelHack",
  "TechCrunch Disrupt Hack",
  "MLH Local Hack Day",
  "Node.js Interactive Sprints",
  "Open Source Saturday",
  "NASA Space Apps Challenge",
  "EthGlobal",
  "Solana Breakpoint",
  "Code for America Summit",
  "Rails Girls Workshop",
  "DjangoGirls",
  "Hard Fork Hack",
  "ByteSized Hackathon",
  "The Big Code Challenge",
  "Zero Trust World",
  "CryptoForge",
  "AppBlitz",
  "Build with Gemini Summit",
  // Creative/Futuristic Names
  "CodeConflux",
  "Quantum Quandary",
  "NeuralNexus",
  "Silicon Synergy",
  "ByteBlast",
  "Algorithm Arena",
  "Digital Dynamo",
  "FutureFlux",
  "CyberSynapse",
  "Infotech Inception",
  "TitanTech Summit",
  "Binary Blast",
  "Matrix Meetup",
  "Edge Computing Expo",
  "Web3 Waves",
  "Prompt Engineering Party",
  "Low-Code Loft",
  "DevRelCon",
  "The Documentation Derby",
  "Open Source Odyssey",
  "SaaS Solutions Summit",
  "The Deployment Disco",
  "CI/CD Carnival",
  "GraphQL Gala",
  "Tailwind Track",
] as const;

export default EVENTS_CONSTANT;
